name: deploy-application

on:
  push:
    branches:
      - master

jobs:
  deploy-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn build
      - name: Configure Google Cloud Credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Upload build files
        run: |
          gsutil cp -r build/* gs://${{ secrets.BUCKET_NAME }}
