name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    container: cypress/browsers:node10.16.3-chrome80-ff73
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: npx serve build/ -l 3000
          wait-on: http://localhost:3000
        env:
          SKIP_PREFLIGHT_CHECK: true
